import { Category } from './category';
import { User } from './user';

export class Game {
  static consoles = [
    '32X',
    '3DO',
    '3DS',
    '3DSVC',
    'AES',
    'Amiga',
    'Android',
    'AppleII',
    'AppleIIGS',
    'Arcade',
    'Archimedes',
    'Arduboy',
    'Atari2600',
    'Atari5200',
    'Atari7800',
    'Atari8bit',
    'AtariFlashback',
    'AtariST',
    'BBCMicro',
    'C64',
    'CD-i',
    'CD32',
    'ColecoVision',
    'CommodoreCDTV',
    'CPC',
    'D32-64',
    'Dreamcast',
    'DS',
    'FCF',
    'FDS',
    'fireTV',
    'G&W',
    'GameCom',
    'GameGear',
    'GB',
    'GBA',
    'GBC',
    'GBI',
    'GBP',
    'GCN',
    'Genesis',
    'GraphCalc',
    'Index',
    'Intellivision',
    'iOS',
    'iQuePlayer',
    'Jaguar',
    'JaguarCD',
    'Java',
    'Linux',
    'Lynx',
    'Mac',
    'MegaNet',
    'MS-DOS',
    'MSX',
    'MSX2',
    'N-Gage',
    'N64',
    'NES',
    'NESClassic',
    'New3DS',
    'New3DSVC',
    'NGCD',
    'NGMini',
    'NGPC',
    'NGX',
    'Oculus',
    'Oric',
    'Ouya',
    'PalmOS',
    'PC',
    'PC-98',
    'PC88',
    'PCFX',
    'PCW',
    'PKMiNi',
    'Plug&Play',
    'PlayStation',
    'PlayStation 2',
    'PlayStation 3',
    'PlayStation 4',
    'PlayStation 4 Pro',
    'PlayStation 5',
    'PlayStation Classic',
    'PlayStation N',
    'PlayStation Now',
    'PlayStation P',
    'PlayStation TV',
    'PlayStation Vita',
    'Roku',
    'Satellaview',
    'Saturn',
    'SCV',
    'SegaCD',
    'SGB',
    'SGB2',
    'SharpX1',
    'Shield',
    'SMS',
    'SNES',
    'SNESClassic',
    'Stadia',
    'Switch',
    'SwitchVC',
    'Tabletop',
    'TG-16',
    'TG16CD',
    'TI-99',
    'Tiger',
    'Towns',
    'V.Smile',
    'VIC-20',
    'VirtualBoy',
    'Vive',
    'Web',
    'Wii',
    'WiiU',
    'WiiUVC',
    'WiiVC',
    'WindowsMR',
    'WindowsPhone',
    'WonderSwan',
    'WSC',
    'X360',
    'X360Arcade',
    'X68000',
    'Xbox',
    'XboxOne',
    'XboxOneS',
    'XboxOneX',
    'XboxSeriesS',
    'XboxSeriesX',
    'Zeebo',
    'ZXSpectrum',
  ];

  id: number;
  name: string;
  description: string;
  console: string;
  ratio: string;
  categories: Category[];
  user: User;
  emulated: boolean;
  visible: boolean;
  submissionId: number;
  status: string;

  constructor() {
    this.console = Game.consoles[0];
    this.categories = [];
    this.user = new User();
  }
}
