name: Compile code

on:
  push:
    branches-ignore:
      - v1
      - master
      - development

jobs:
  lint_code:
    name: Lint code
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-lint
      cancel-in-progress: true

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'

      - name: Install deps
#        run: npm ci
        run: npm install

      - name: lint code
        run: npm run lint

  build_image:
    name: Build image
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: oengusio/frontend:v1
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            PROFILE=production

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
